name: Laravel

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  laravel-tests:

    runs-on: self-hosted

    steps:
    - uses: setup-php
      with:
        php-version: '8.1.2'
    - uses: actions/checkout@v3
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
